### PR TITLE
Fix typo in test name

### PR DESCRIPTION
**Pull request by pimterry**

### CODE REVIEW

**Comment by thgreasi** [comment]
2 hours later .... typo fix merged!!!

**Comment by thgreasi** [comment]
I wonder how much CO2 is emitted whenever we merge an SDK PR.

**Comment by thgreasi** [comment]
Oh, just saw that no-ckecks label :smile:

**Comment by pimterry** [comment]
Hehe, yep, it's all a bit over the top. Good to check though! Maybe that typo'd test name was the only thing holding the SDK together, and without it nothing would work any more...

**Pull request merged**
