### PR TITLE
Update to resin-pine 8.x

### PR DESCRIPTION
**Pull request by Page-**
This will only break things if you are passing custom options,
the relevant breakages are:
* Remove deprecated expand behaviour, eg `$expand: { x: 'y' }`
* Remove deprecated automatic $ prefixing for `options`,
    eg `select: 'id'`

Change-type: major
Signed-off-by: Pagan Gazzard <page@resin.io>

### CODE REVIEW

**Comment by thgreasi** [comment]
That's not going to be passing on resin-ci until we get secrets in there.
We should also revisit the typings as well to reflect the resin-pine changes. Might find some time to give it try later this week if no one does.

**Comment by Page-** [comment]
What do you mean @thgreasi ?  I think those changes were already in the typings from before as the typings never included the deprecated formats

**Comment by thgreasi** [comment]
Yea you are right @Page- , they indeed do not include any of these :)

**Comment by Page-** [comment]
Done @pimterry

**Comment by pimterry** [comment]
I'd love to squeeze this in with other breaking changes, but I'm not sure we've got any coming in the very short term, unless you're planning some for orgs? If they're not super soon though (like, within the next week max), imo we can just do a major bump now and another later on, that's better than holding this for ages.

**Comment by pimterry** [comment]
This bump has ended up being included in the breaking rename PR as we've moved to balena-pine, so I'm going to close this.

**Pull request closed without merging**
