### PR TITLE
update nodejs test versions

### PR DESCRIPTION
**Pull request by emirotin**

### CODE REVIEW

**Comment by emirotin** [comment]
There seem to be problems with simultaneous tests and probably that's why you had different apps set for AppVeyor

**Comment by jviotti** [comment]
Do you have access to Appveyor to edit the private environment variables to match the ones that were in the Appveyor matrix yourself?

**Comment by jviotti** [comment]
I double checked, and since you're part of the organization, and certain teams of it, you should be able to access the Appveyor project settings without issues. Let me know if this is not the case and I'll send an explicit invitation.

**Comment by emirotin** [comment]
Closing this as the browser PR also makes these changes.

**Pull request closed without merging**
