### PR TITLE
typings: Properly type User to Application navigation

### PR DESCRIPTION
**Pull request by thgreasi**
Resolves: #561
Change-type: patch
Signed-off-by: Thodoris Greasidis <thodoris@resin.io>

### CODE REVIEW

**Comment by thgreasi** [comment]
@resin-ci retest

**Comment by thgreasi** [comment]
@resin-ci retest

**Comment by thgreasi** [comment]
@resin-ci retest

**Comment by thgreasi** [comment]
@resin-ci retest

**Comment by thgreasi** [comment]
@resin-ci retest

**Comment by brownjohnf** [comment]
@resin-ci retest

**Pull request merged**
